export const shiftGreetings = {
  ems: [
    "{name} — stay sharp, drive safe, save lives.",
    "Alright {name}, try not to blow out the siren today. Stay sharp out there.",
    "Coffee first, {name}. Then we save lives. In that exact order.",
    "Keep the shiny side up and the rubber side down today, {name}. Have a good shift!",
    "No 5150s before lunch today, {name}. After that, you're on your own.",
    "Hey {name}, remember: BSI, scene safe, and don't drop the stretcher.",
    "Another day, another dollar... or whatever we make here. Have a good one, {name}.",
    "Try to keep the rig in one piece today, {name}. The mechanic is crying.",
    "Welcome to the start of your shift, {name}. May your transports be short and your coffees be hot.",
    "Load and go, {name}. Load and go.",
    "Hey {name}, just a heads up: the Frequent Flyers are active today.",
    "Stay caffeinated, {name}. It's going to be one of those shifts.",
    "Remember {name}, all bleeding stops eventually. Have a good shift!",
    "Let's get out there and do some good today, {name}.",
    "Keep your head on a swivel today, {name}.",
    "Welcome to the shift, {name}. May your IVs always hit on the first try.",
    "Hey {name}, don't forget to chart. Have a good shift!",
    "Stay safe out there, {name}. Your dinner is waiting for you at home.",
    "May the traffic lights be ever in your favor, {name}.",
    "Alright {name}, let's make this shift count.",
    "{name}, the streets are calling. Answer them safely.",
    "Have a smooth shift, {name}. And please don't back into the bay door again.",
    "Hey {name}, remember: we're here to help, even when they don't want it.",
    "Stay frosty, {name}. It's a jungle out there.",
    "{name}, let's hope for a quiet shift... just kidding, don't say the Q word!",
    "Your chariot awaits, {name}. Let's go save some lives.",
    "Hey {name}, keep calm and carry the O2 bag.",
    "May your monitor batteries always be 100%, {name}.",
    "Alright {name}, let's roll. Be safe, be smart.",
    "{name} — ready to turn sirens into smiles today?"
  ],
  fire: [
    "{name} — stay low, move fast, watch your six.",
    "Hey {name}, try not to burn the chili tonight.",
    "Keep the wet stuff on the red stuff today, {name}.",
    "Another day at the firehouse, {name}. Let's hope the recliner is comfortable.",
    "Welcome to the shift, {name}. May your SCBA always be full.",
    "Alright {name}, let's keep the shiny side up. Have a safe shift.",
    "Hey {name}, remember: everybody goes home.",
    "Let's get out there and do some aggressive interior firefighting today, {name}. (Or just rescue a cat).",
    "Stay safe out there, {name}. We need you back here for dinner.",
    "Hey {name}, the truck is washed, the boots are shined. Let's go.",
    "{name} — ready to put the wet stuff on the red stuff?",
    "May your hose lines never kink, {name}.",
    "Alright {name}, let's make some noise and save some lives.",
    "Hey {name}, keep checking that primary search. Have a good shift.",
    "Stay sharp, {name}. Fire is unpredictable.",
    "{name}, let's hope for a quiet... no, I'm not saying it.",
    "Welcome to the shift, {name}. Let's get to work.",
    "Hey {name}, don't forget to check your air.",
    "{name} — brotherhood and bravery. Let's have a great shift.",
    "Alright {name}, let's roll out and make a difference today.",
    "May the hydrants always be close, {name}.",
    "Hey {name}, keep your head down and your spirits up.",
    "Stay low and go, {name}.",
    "{name}, let's keep the community safe today.",
    "Welcome back, {name}. Let's hope the tones don't drop during dinner.",
    "Hey {name}, remember: risk a little to save a little, risk a lot to save a lot.",
    "{name} — fully involved and ready to go.",
    "Alright {name}, let's show them how it's done.",
    "May your turnout gear always be dry when you put it on, {name}.",
    "{name} — let's go make the department proud today."
  ],
  police: [
    "{name} — stay safe out there. We've got your back.",
    "Hey {name}, keep your head on a swivel today.",
    "Code 4 all day, {name}. Have a quiet shift.",
    "Another day, another donut joke. Stay safe, {name}.",
    "Welcome to the shift, {name}. Watch your six.",
    "Alright {name}, let's keep the peace today.",
    "Hey {name}, remember: complacency kills. Stay sharp.",
    "Let's get out there and do some good police work today, {name}.",
    "Stay safe, {name}. Your family is waiting for you to come home.",
    "Hey {name}, the cruiser is fueled and ready. Let's roll.",
    "{name} — ready to serve and protect?",
    "May your radio always have clear reception, {name}.",
    "Alright {name}, let's enforce the law fairly and firmly.",
    "Hey {name}, keep your wits about you. Have a good shift.",
    "Stay frosty, {name}. It's a wild world out there.",
    "{name}, let's hope for a boring shift.",
    "Welcome to the shift, {name}. Let's get to work.",
    "Hey {name}, don't forget your vest.",
    "{name} — courage and commitment. Let's have a great shift.",
    "Alright {name}, let's roll out and keep the streets safe.",
    "May your backup always arrive quickly, {name}.",
    "Hey {name}, keep calm and carry on.",
    "Watch your speed out there, {name}. We don't want to give YOU a ticket.",
    "{name}, let's make a positive impact today.",
    "Welcome back, {name}. Let's hope the paperwork is light today.",
    "Hey {name}, remember: treat everyone with respect, but have a plan to...",
    "{name} — 10-8 and ready for calls.",
    "Alright {name}, let's show them what real policing looks like.",
    "May your coffee stay hot and your shift go fast, {name}.",
    "{name} — let's go make the city proud today."
  ]
}
